### ISSUE TITLE
[bug] error: sorry, too many clients already

### ISSUE THREAD

**Issue by zmts** [SpoonX/wetland#238]
Hi here!

I found some issues

After sending over 10 requests
I got reminder from node.js
```
(node:55726) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 beforeExit listeners added. Use emitter.setMaxListeners() to increase limit
```

And then after ~20-25 requests per ~five seconds
I got list of errors
```
error: sorry, too many clients already
Error
    at new ErrorWrapper (/Volumes/DATA/dev/supra-api-nodejs/util/error.js:4:18)
    at GETById.MANAGER.getRepository.findOne.then.catch.error (/Volumes/DATA/dev/supra-api-nodejs/repository/Base.js:60:33)
    at tryCatcher (/Volumes/DATA/dev/supra-api-nodejs/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Volumes/DATA/dev/supra-api-nodejs/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Volumes/DATA/dev/supra-api-nodejs/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Volumes/DATA/dev/supra-api-nodejs/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Volumes/DATA/dev/supra-api-nodejs/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/Volumes/DATA/dev/supra-api-nodejs/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Volumes/DATA/dev/supra-api-nodejs/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Volumes/DATA/dev/supra-api-nodejs/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
```
```
node v8.9.1
postresql 9.6
max_connections: 100 (in postgresql.conf)
```
Project that currently I working on. Maybe it can help.
https://github.com/zmts/supra-api-nodejs/blob/orm-wetland/repository/BaseRepository.js

Probably its related with pool size. In Knex we got pool option 
```
pool: { min: 0, max: 7 }
```
Can I configure that option in Wetland? 
Or some any solutions to fix it ?

**Comment by RWOverdijk** [comment]
Hello @zmts 

Yes! Those options can be passed in. In your case, it would just be part of the regular config. This does indicate a generally larger problem.

If you want to use knex pools, simply add it to your store config (in `connection`). If that doesn't work please post your config so I can help you out.

**Comment by RWOverdijk** [comment]
@zmts I'm sorry but this sounds like you're doing something else wrong. Are you making a new wetland instance every time?

**Comment by zmts** [comment]
You right! I spawn wetland instance each time. Thank you for support! All works brilliant!

**Comment by RWOverdijk** [comment]
I'm glad you were able to track down the issue! 

For now I'll close this issue then. Feel free to ask related questions on gitter in the future.

Happy coding.
